In [51]:
!pip install emoji

In [52]:
import re
import pandas as pd
from nltk.corpus import stopwords
from wordcloud import WordCloud, STOPWORDS
import emoji
import spacy
from sklearn.model_selection import train_test_split

In [54]:
import nltk
nltk.download('vader_lexicon')
nltk.download('words')

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!
[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Package words is already up-to-date!


True

In [55]:
import matplotlib.pyplot as plt
%matplotlib inline

In [56]:
from google.colab import drive
drive.mount('/content/drive')
par1 = pd.read_csv('/content/drive/MyDrive/BNB_data1.csv')
par3 = pd.read_csv('/content/drive/MyDrive/usdt_data3.csv')
par4 = pd.read_csv('/content/drive/MyDrive/BTC.csv')
par4.drop('Unnamed: 0', axis = 1, inplace = True)
par5 = pd.read_csv('/content/drive/MyDrive/BNB_data2.csv')
df = pd.concat([par1, par3, par4, par5])

In [60]:
nlp = spacy.load('en_core_web_sm', disable=['parser', 'ner'])

In [61]:
for i in range (len(df)):
  df.iloc[i,2] = str(df.iloc[i,2])

In [62]:
df

Datetime  ...         Username
0      2021-12-30 23:59:43+00:00  ...          piral03
1      2021-12-30 23:59:24+00:00  ...        ctalerts7
2      2021-12-30 23:59:23+00:00  ...        ctalerts7
3      2021-12-30 23:59:22+00:00  ...       Solitacore
4      2021-12-30 23:59:19+00:00  ...       mas_ibrafx
...                          ...  ...              ...
50089  2021-11-25 14:48:47+00:00  ...   aliiiirezaaaaa
50090  2021-11-25 14:48:42+00:00  ...  JohnGom71209530
50091  2021-11-25 14:48:36+00:00  ...  ChristianMalden
50092  2021-11-25 14:48:36+00:00  ...      yakobus0720
50093  2021-11-25 14:48:35+00:00  ...        etymoni21

[261224 rows x 4 columns]

In [63]:
# filter out non-English
for i in range (len(df)):
  df.iloc[i,2] = ' '.join(re.sub('[^A-Za-z0-9]',' ', df.iloc[i,2]).split())

In [64]:
# emoji to string conversion
for i in range (len(df)):
  df.iloc[i,2] = emoji.demojize(df.iloc[i,2])
  df.iloc[i,2] = df.iloc[i,2].replace(":"," ")
  df.iloc[i,2] = ' '.join(df.iloc[i,2].split())

In [65]:
# remove urls
for i in range (len(df)):
  df.iloc[i,2] = ' '.join(re.sub("(\w+:\/\/\S+)", " ", df.iloc[i,2]).split())

In [66]:
# to lowercase letters
df['new_Text'] = df['Text'].apply(lambda x: " ".join(x.lower() for x in x.split()))
df['new_Text'].head()

0                                  binance turkish bnb
1    1 000 btc 46 917 121 usd wallet to coinbase ht...
2    1 000 btc 46 917 121 usd wallet to coinbase ht...
3    vote us on top100token bnb bsc solt solitacore...
4    mbah mijan robowolf8 fianby holder is the winn...
Name: new_Text, dtype: object

In [67]:
# remove special characters
df['new_Text'] = df['new_Text'].str.replace('[^\w\s]','')
df['new_Text'].head()

0                                  binance turkish bnb
1    1 000 btc 46 917 121 usd wallet to coinbase ht...
2    1 000 btc 46 917 121 usd wallet to coinbase ht...
3    vote us on top100token bnb bsc solt solitacore...
4    mbah mijan robowolf8 fianby holder is the winn...
Name: new_Text, dtype: object

In [68]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [69]:
stop = stopwords.words('english')
df['new_Text'] = df['new_Text'].apply(lambda x: " ".join(x for x in x.split() if x not in stop))
df.head(20)

Datetime  ...                                           new_Text
0   2021-12-30 23:59:43+00:00  ...                                binance turkish bnb
1   2021-12-30 23:59:24+00:00  ...  1 000 btc 46 917 121 usd wallet coinbase https...
2   2021-12-30 23:59:23+00:00  ...  1 000 btc 46 917 121 usd wallet coinbase https...
3   2021-12-30 23:59:22+00:00  ...  vote us top100token bnb bsc solt solitacore to...
4   2021-12-30 23:59:19+00:00  ...  mbah mijan robowolf8 fianby holder winner buy ...
5   2021-12-30 23:58:55+00:00  ...  bnb price 518 4 right compared last tweet pric...
6   2021-12-30 23:58:53+00:00  ...  marketplace update finally added ability trade...
7   2021-12-30 23:55:01+00:00  ...  buy exchange grow crypto firmly ledger gadget ...
8   2021-12-30 23:54:15+00:00  ...  metaclashgame je dois faire partie des gagnant...
9   2021-12-30 23:52:32+00:00  ...  top 5 crypto prices 24h change btc eth bnb sol...
10  2021-12-30 23:52:05+00:00  ...  10 criptomoedas com maior valor de mercado coi...
11  2021-12-30 23:49:30+00:00  ...  airdrop seger langsung gas https co gdr4zd0qci...
12  2021-12-30 23:48:29+00:00  ...  la cr de la cr crypto bscgem bnb btc bsc defi ...
13  2021-12-30 23:48:13+00:00  ...  crypto lot like tree every new year new layer ...
14  2021-12-30 23:47:34+00:00  ...                                binance turkish bnb
15  2021-12-30 23:47:34+00:00  ...  hodl lfsh bullrun trustwallet doge bnb binance...
16  2021-12-30 23:47:29+00:00  ...  airdrop fresh bgt langsung gas https co xysadv...
17  2021-12-30 23:47:02+00:00  ...  btc 47061 8 eth 3706 57 bnb 517 9 ada 1 35 xrp...
18  2021-12-30 23:46:37+00:00  ...  good morning work hard project help change wor...
19  2021-12-30 23:45:49+00:00  ...  btc bitcoin 100 increase longs past week longs...

[20 rows x 5 columns]

In [70]:
def space(comment):
    doc = nlp(comment)
    return " ".join([token.lemma_ for token in doc])
df['new_Text']= df['new_Text'].apply(space)
df.head(20)

Datetime  ...                                           new_Text
0   2021-12-30 23:59:43+00:00  ...                                binance turkish bnb
1   2021-12-30 23:59:24+00:00  ...  1 000 btc 46 917 121 usd wallet coinbase http ...
2   2021-12-30 23:59:23+00:00  ...  1 000 btc 46 917 121 usd wallet coinbase http ...
3   2021-12-30 23:59:22+00:00  ...  vote -PRON- top100token bnb bsc solt solitacor...
4   2021-12-30 23:59:19+00:00  ...  mbah mijan robowolf8 fianby holder winner buy ...
5   2021-12-30 23:58:55+00:00  ...  bnb price 518 4 right compare last tweet price...
6   2021-12-30 23:58:53+00:00  ...  marketplace update finally add ability trade t...
7   2021-12-30 23:55:01+00:00  ...  buy exchange grow crypto firmly ledger gadget ...
8   2021-12-30 23:54:15+00:00  ...  metaclashgame je dois faire partie des gagnant...
9   2021-12-30 23:52:32+00:00  ...  top 5 crypto price 24h change btc eth bnb sol ...
10  2021-12-30 23:52:05+00:00  ...  10 criptomoedas com maior valor de mercado coi...
11  2021-12-30 23:49:30+00:00  ...  airdrop seger langsung gas https co gdr4zd0qci...
12  2021-12-30 23:48:29+00:00  ...  la cr de la cr crypto bscgem bnb btc bsc defi ...
13  2021-12-30 23:48:13+00:00  ...  crypto lot like tree every new year new layer ...
14  2021-12-30 23:47:34+00:00  ...                                binance turkish bnb
15  2021-12-30 23:47:34+00:00  ...  hodl lfsh bullrun trustwallet doge bnb binance...
16  2021-12-30 23:47:29+00:00  ...  airdrop fresh bgt langsung gas https co xysadv...
17  2021-12-30 23:47:02+00:00  ...  btc 47061 8 eth 3706 57 bnb 517 9 ada 1 35 xrp...
18  2021-12-30 23:46:37+00:00  ...  good morning work hard project help change wor...
19  2021-12-30 23:45:49+00:00  ...  btc bitcoin 100 increase long past week long 3...

[20 rows x 5 columns]

In [71]:
def get_sentence_mean_vector(morphs):
    vector = []
    for i in morphs:
        try:
            vector.append(models.wv[i])
        except KeyError as e:
            pass
    try:
        return np.mean(vector, axis=0)
    except IndexError as e:
        pass

In [72]:
# installword2vec model
#!pip install gensim
from gensim.models import Word2Vec

models = Word2Vec(df['new_Text'], size=8, window=3, negative=3, min_count=3, workers=3, sg=1)

In [73]:
import numpy as np

In [157]:
df['wv'] = df['new_Text'].map(get_sentence_mean_vector)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [158]:
df, df_test = train_test_split(df, test_size=0.2, random_state=7)

In [159]:
from sklearn.cluster import KMeans
import time

word_vectors = df.wv.to_list() 
num_clusters = 3

In [160]:
word_vectors[:10]

[array([-0.04684939,  0.35047993, -0.1218944 ,  0.25916937,  0.2661923 ,
        -0.47090742, -0.08102216,  0.38459015], dtype=float32),
 array([-0.04836779,  0.32333988, -0.08815928,  0.25667202,  0.2695844 ,
        -0.4313411 , -0.07719078,  0.43343788], dtype=float32),
 array([-0.24301513,  0.21482077,  0.04306023,  0.25640413,  0.531842  ,
        -0.08627678,  0.11412951,  0.2344836 ], dtype=float32),
 array([-0.27820757,  0.19619332,  0.04397835,  0.32397282,  0.5108317 ,
        -0.12602101,  0.0498492 ,  0.18994252], dtype=float32),
 array([-0.14243433,  0.27132723, -0.06701065,  0.29145485,  0.38973138,
        -0.26708502, -0.02255076,  0.32669738], dtype=float32),
 array([ 0.00761578,  0.326563  , -0.17263885,  0.26797852,  0.24188396,
        -0.4379321 , -0.12000602,  0.48199135], dtype=float32),
 array([-0.01664698,  0.316164  , -0.10570072,  0.26102668,  0.28725567,
        -0.3774952 , -0.10568456,  0.45908368], dtype=float32),
 array([-0.44683254,  0.14213362,  0.1018

In [161]:
a = []
for i in range(len(word_vectors)):
    if word_vectors[i].dtype != np.float32:
      print(i)
         
a

[]

In [148]:
# word_vectors = np.delete(word_vectors,174002)

In [154]:
word_vectors = list(word_vectors)

In [163]:
# define Kmeans & fit and predict
kmeans_clustering = KMeans(n_clusters = num_clusters)
idx = kmeans_clustering.fit_predict(word_vectors)

In [136]:
df = df.drop(df.index[174002])

In [164]:
df['category'] = idx

In [165]:
df['category']

11883    2
37966    2
52171    1
30274    1
11002    0
        ..
19740    2
32838    2
59833    2
42112    2
38012    0
Name: category, Length: 167180, dtype: int32

In [170]:
df[['new_Text','wv']]

new_Text                                                 wv
11883  bull back bch xrparmy xrp xrp xrpcommunity rip...  [-0.046849392, 0.35047993, -0.1218944, 0.25916...
37966  tableau des yield chez swissborg btc eth chsb ...  [-0.048367787, 0.32333988, -0.08815928, 0.2566...
52171  top 10 cryptocurrency live price 03 10 dec 13 ...  [-0.24301513, 0.21482077, 0.04306023, 0.256404...
30274  binance btcusdt short liquidation 5 148 btc 48...  [-0.27820757, 0.19619332, 0.043978352, 0.32397...
11002    btc rise 7 72 last week price currently 63063 3  [-0.14243433, 0.27132723, -0.06701065, 0.29145...
...                                                  ...                                                ...
19740  strong movers usdt 1 sushi sushi 2 okb okb 3 x...  [-0.061893728, 0.2994363, -0.03698988, 0.26205...
32838  market cap top 2 stablecoin show usdt turn pho...  [-0.03396917, 0.32077008, -0.122975506, 0.2603...
59833  eljaboom cz binance although start tweet march...  [-0.042152084, 0.29543668, -0.061849527, 0.281...
42112  scan result 1h usdt pair binance top 5 bullish...  [-0.080649644, 0.2871952, -0.058327936, 0.2654...
38012  1 744 416 usdt 1 744 416 usd move unknown wall...  [-0.18137445, 0.22776861, -0.022048699, 0.2942...

[167180 rows x 2 columns]

In [171]:
from sklearn.manifold import TSNE

X = df['wv'].to_list()

y = df['category'].to_list()

import os.path
import pickle

tsne_filepath = 'tsne3000.pkl'

# File Cache
if not os.path.exists(tsne_filepath):
    tsne = TSNE(random_state=41)
    tsne_points = tsne.fit_transform(X)
    with open(tsne_filepath, 'wb+') as f:
        pickle.dump(tsne_points, f)
else: # Cache Hits!
    with open(tsne_filepath, 'rb') as f:
        tsne_points = pickle.load(f)

tsne_df = pd.DataFrame(tsne_points, index=range(len(X)), columns=['x_coord', 'y_coord'])
tsne_df['tweets'] = df['new_Text'].to_list()
tsne_df['cluster_no'] = y

/usr/local/lib/python3.7/dist-packages/sklearn/manifold/_t_sne.py:783: FutureWarning: The default initialization in TSNE will change from 'random' to 'pca' in 1.2.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/manifold/_t_sne.py:793: FutureWarning: The default learning rate in TSNE will change from 200.0 to 'auto' in 1.2.
  FutureWarning,


In [172]:
tsne_df

x_coord  ...  cluster_no
0       10.246196  ...           2
1        7.345689  ...           2
2      -34.058857  ...           1
3      -14.554256  ...           1
4       18.849442  ...           0
...           ...  ...         ...
167175  14.692942  ...           2
167176   5.322515  ...           2
167177  17.482107  ...           2
167178  29.750538  ...           2
167179   4.399596  ...           0

[167180 rows x 4 columns]

In [ ]:
#scatter plot
groups = tsne_df.groupby('cluster_no')

fig, ax = plt.subplots()

for name, group in groups:

    ax.plot(group.x_coord, 
            group.y_coord, 
            marker='o', 
            linestyle='',
            label=name)

ax.legend(fontsize=12, loc='upper right') # legend position
plt.title('Scatter Plot of wordvector by matplotlib', fontsize=20)
plt.xlabel('X_coord', fontsize=14)
plt.ylabel('Y_coord', fontsize=14)
plt.show()

In [174]:
cl2 = tsne_df.loc[tsne_df['cluster_no']==2]

In [175]:
cl1 = tsne_df.loc[tsne_df['cluster_no']==1]

In [176]:
cl0 = tsne_df.loc[tsne_df['cluster_no']==0]

In [192]:
cl0[30:50]

x_coord  ...  cluster_no
189  29.206881  ...           0
203  23.079712  ...           0
223 -19.400324  ...           0
228  34.399471  ...           0
229  30.000082  ...           0
233   7.948792  ...           0
238   6.176567  ...           0
239   6.195035  ...           0
241  15.916296  ...           0
242  -1.355526  ...           0
244  26.621557  ...           0
245  18.235447  ...           0
249  26.115089  ...           0
252  17.122339  ...           0
253   8.706056  ...           0
255  22.234249  ...           0
259  16.591166  ...           0
270   1.332911  ...           0
274  11.187364  ...           0
275  16.854227  ...           0

[20 rows x 4 columns]

In [181]:
para = min(len(cl2),len(cl1),len(cl0))

In [182]:
part1 = cl1.sample(n=para)
part2 = cl2.sample(n=para)
part0 = cl0.sample(n=para)

tsne_df = pd.concat([part1, part2, part0])

In [183]:
from sklearn import svm
X = tsne_df[['x_coord','y_coord']]
y = tsne_df['cluster_no']

In [185]:
model = svm.SVC(gamma = 0.5 , C = 0.5)
model.fit(X,y)

SVC(C=0.5, gamma=0.5)

In [193]:
from sklearn.manifold import TSNE

word_vectors2 = df_test.wv.to_list()
df_test['wv'] = word_vectors2 

X2 = df_test['wv'].to_list()

import os.path
import pickle

tsne_filepath = 'tsne3001.pkl'

# File Cache
if not os.path.exists(tsne_filepath):
    tsne = TSNE(random_state=41)
    tsne_points2 = tsne.fit_transform(X2)
    with open(tsne_filepath, 'wb+') as f:
        pickle.dump(tsne_points2, f)
else: # Cache Hits!
    with open(tsne_filepath, 'rb') as f:
        tsne_points2 = pickle.load(f)

tsne_df2 = pd.DataFrame(tsne_points2, index=range(len(X2)), columns=['x_coord', 'y_coord'])

/usr/local/lib/python3.7/dist-packages/sklearn/manifold/_t_sne.py:783: FutureWarning: The default initialization in TSNE will change from 'random' to 'pca' in 1.2.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/manifold/_t_sne.py:793: FutureWarning: The default learning rate in TSNE will change from 200.0 to 'auto' in 1.2.
  FutureWarning,


In [194]:
tsne_df2

x_coord    y_coord
0     -25.765385 -55.799473
1      48.801498 -12.826547
2      22.489809 -15.507630
3     -49.079788 -29.410473
4      42.246399  31.726158
...          ...        ...
41790  25.659662   9.640702
41791   2.183542 -16.216745
41792  23.715273 -51.475578
41793  16.207993  -0.485354
41794  37.795963  35.114880

[41795 rows x 2 columns]

In [195]:
X_test = tsne_df2[['x_coord','y_coord']]
y_predict = model.predict(X_test)
df_test['cluster_no'] = y_predict

In [196]:
df_test = df_test[['Datetime','cluster_no']]
df_test.describe()

cluster_no
count  41795.000000
mean       1.746644
std        0.632883
min        0.000000
25%        2.000000
50%        2.000000
75%        2.000000
max        2.000000

In [197]:
# greed = 1, neutral = 0, fear = -1 로 바꿈
# calculate the average score for each date
# 0.33 and above : greed, -0.33 <= x <= 0.33 : neutral, -0.33 and below: fear
# date - class table
# compare the results of the day, the day after, and 7 days later 
# accuracy_score(train_y, predicted_y)
# understand the cause

In [198]:
# greed = 1, neutral = 0, fear = -1 
for i in range (len(df_test)):
  if df_test.iloc[i,-1] == 0 :
    df_test.iloc[i,-1] = 1
  elif df_test.iloc[i,-1] == 1:
    df_test.iloc[i,-1] = -1
  else:
    df_test.iloc[i,-1] = 0

In [199]:
df_test.describe()

cluster_no
count  41795.000000
mean       0.063692
std        0.378972
min       -1.000000
25%        0.000000
50%        0.000000
75%        0.000000
max        1.000000

In [200]:
df_test.sort_index()

Datetime  cluster_no
3       2021-08-07 23:56:07+00:00           0
7       2021-12-01 23:59:33+00:00           0
8       2021-12-01 23:57:58+00:00           0
12      2021-12-01 23:59:19+00:00           1
17      2021-12-01 23:55:53+00:00           0
...                           ...         ...
100476  2021-12-02 17:20:18+00:00           0
100478  2021-12-02 17:19:47+00:00           0
100483  2021-12-02 17:17:35+00:00           0
100486  2021-12-02 17:16:42+00:00           0
100487  2021-12-02 17:16:27+00:00           1

[41795 rows x 2 columns]

In [201]:
for i in range (len(df_test)):
  df_test.iloc[i,0] = df_test.iloc[i,0][0:10]

In [250]:
df_final = df_test.groupby('Datetime').sum() 

In [251]:
for i in range(len(df_final)):
  if len(df_final.index[i]) != 10:
    df_final.drop(df_final.index[i])
  else:
    if df_final.index[i][:4] != '2021':
      df_final.drop(df_final.index[i])

In [252]:
df_final

cluster_no
Datetime              
#DAR/#BUSD           0
#DUSK/#USD           0
#MANA/#BNB           0
#SMG/#USDT           0
#VOXEL/#BU           0
...                ...
2021-12-30          31
Coin: $RAY           0
DODO/#BTC            0
Pairs:               0
Via https:           0

[200 rows x 1 columns]

In [206]:
len_date = df_test.groupby('Datetime').size().to_list()

In [253]:
for i in range(len(df_final)):
  df_final.iloc[i,0] = df_final.iloc[i,0] / len_date[i]
df_final

cluster_no
Datetime              
#DAR/#BUSD    0.000000
#DUSK/#USD    0.000000
#MANA/#BNB    0.000000
#SMG/#USDT    0.000000
#VOXEL/#BU    0.000000
...                ...
2021-12-30    0.054386
Coin: $RAY    0.000000
DODO/#BTC     0.000000
Pairs:        0.000000
Via https:    0.000000

[200 rows x 1 columns]

In [231]:
label = pd.read_csv('/content/drive/MyDrive/crypto_fg.csv')
label

Datetime Class
0     01-02-2022  Fear
1     01-01-2022  Fear
2     12-31-2021  Fear
3     12-30-2021  Fear
4     12-29-2021  Fear
...          ...   ...
1424  02-05-2018  Fear
1425  02-04-2018  Fear
1426  02-03-2018  Fear
1427  02-02-2018  Fear
1428  02-01-2018  Fear

[1429 rows x 2 columns]

In [232]:
type(label.iloc[1,1])

str

In [233]:
import datetime
format = '%m-%d-%Y'
for i in range(len(label)):
  label.iloc[i,0] = dt_datetime = datetime.datetime.strptime(label.iloc[i,0],format)
  label.iloc[i,0] = str(label.iloc[i,0])

In [211]:
label

Datetime Class
0     2022-01-02 00:00:00  Fear
1     2022-01-01 00:00:00  Fear
2     2021-12-31 00:00:00  Fear
3     2021-12-30 00:00:00  Fear
4     2021-12-29 00:00:00  Fear
...                   ...   ...
1424  2018-02-05 00:00:00  Fear
1425  2018-02-04 00:00:00  Fear
1426  2018-02-03 00:00:00  Fear
1427  2018-02-02 00:00:00  Fear
1428  2018-02-01 00:00:00  Fear

[1429 rows x 2 columns]

In [234]:
for i in range (len(label)):
  label.iloc[i,0] = label.iloc[i,0][0:10]

In [235]:
label

Datetime Class
0     2022-01-02  Fear
1     2022-01-01  Fear
2     2021-12-31  Fear
3     2021-12-30  Fear
4     2021-12-29  Fear
...          ...   ...
1424  2018-02-05  Fear
1425  2018-02-04  Fear
1426  2018-02-03  Fear
1427  2018-02-02  Fear
1428  2018-02-01  Fear

[1429 rows x 2 columns]

In [214]:
from google.colab import files
import csv

In [215]:
df_final.to_csv('df_final.csv', index = False, encoding = 'utf-8')
files.download('df_final.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [230]:
label.to_csv('label.csv', index = False, encoding = 'utf-8')
files.download('label.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [254]:
df_final = pd.DataFrame(df_final[10:196])

In [255]:
df_final

cluster_no
Datetime              
2021-06-26    0.083744
2021-06-27    0.006173
2021-06-28    0.010309
2021-06-29    0.023474
2021-06-30    0.084270
...                ...
2021-12-26    0.086283
2021-12-27    0.095238
2021-12-28    0.063670
2021-12-29    0.021195
2021-12-30    0.054386

[186 rows x 1 columns]

In [239]:
label.sort_index(ascending = True, inplace=True)
label[:5]

Datetime Class
0  2022-01-02  Fear
1  2022-01-01  Fear
2  2021-12-31  Fear
3  2021-12-30  Fear
4  2021-12-29  Fear

In [225]:
label.loc[label['Datetime']=='2021-06-26']

Datetime Class
190  2021-06-26  Fear

In [228]:
label.loc[label['Datetime']=='2021-12-31']

Datetime Class
2  2021-12-31  Fear

In [240]:
label = pd.DataFrame(label[2:190])
label.sort_index(ascending= False, inplace = True)
label

Datetime Class
189  2021-06-27  Fear
188  2021-06-28  Fear
187  2021-06-29  Fear
186  2021-06-30  Fear
185  2021-07-01  Fear
..          ...   ...
6    2021-12-27  Fear
5    2021-12-28  Fear
4    2021-12-29  Fear
3    2021-12-30  Fear
2    2021-12-31  Fear

[188 rows x 2 columns]

In [243]:
label.set_index('Datetime')

Class
Datetime        
2021-06-27  Fear
2021-06-28  Fear
2021-06-29  Fear
2021-06-30  Fear
2021-07-01  Fear
...          ...
2021-12-27  Fear
2021-12-28  Fear
2021-12-29  Fear
2021-12-30  Fear
2021-12-31  Fear

[188 rows x 1 columns]

In [263]:
df_fianl = pd.DataFrame(df_final[1:182])

In [256]:
for i in range(len(df_final)):
  if df_final.iloc[i,0] > 0.03:
    df_final.iloc[i,0] = 'Fear'
  elif df_final.iloc[i,0] < -0.03:
    df_final.iloc[i,0] = 'Greed'
  else:
    df_final.iloc[i,0] = 'Neutral'
df_final    

cluster_no
Datetime             
2021-06-26       Fear
2021-06-27    Neutral
2021-06-28    Neutral
2021-06-29    Neutral
2021-06-30       Fear
...               ...
2021-12-26       Fear
2021-12-27       Fear
2021-12-28       Fear
2021-12-29    Neutral
2021-12-30       Fear

[186 rows x 1 columns]

In [266]:
df_final = df_fianl

In [277]:
df_final[:10]

cluster_no
Datetime             
2021-06-27    Neutral
2021-06-28    Neutral
2021-06-29    Neutral
2021-06-30       Fear
2021-07-01       Fear
2021-07-02       Fear
2021-07-03       Fear
2021-07-04       Fear
2021-07-05    Neutral
2021-07-06       Fear

In [278]:
df_final2[:10]

cluster_no
Datetime             
2021-06-27    Neutral
2021-06-28    Neutral
2021-06-29    Neutral
2021-06-30       Fear
2021-07-01       Fear
2021-07-02       Fear
2021-07-03       Fear
2021-07-04       Fear
2021-07-05    Neutral
2021-07-06       Fear

In [261]:
score = 0
for i in range(180):
  if df_final.iloc[i,0] == label.iloc[i,1]:
    score += 1
score

75

In [268]:
label

Datetime Class
189  2021-06-27  Fear
188  2021-06-28  Fear
187  2021-06-29  Fear
186  2021-06-30  Fear
185  2021-07-01  Fear
..          ...   ...
6    2021-12-27  Fear
5    2021-12-28  Fear
4    2021-12-29  Fear
3    2021-12-30  Fear
2    2021-12-31  Fear

[188 rows x 2 columns]

In [273]:
for k in range(8):
  scores = 0  
  for i in range(180):
    if df_final.iloc[i,0] == label.iloc[i+k,1]:
      scores += 1
  print(f'after {k}days accurarcy is {scores/181}')

after 0days accurarcy is 0.39226519337016574
after 1days accurarcy is 0.4143646408839779
after 2days accurarcy is 0.4198895027624309
after 3days accurarcy is 0.4198895027624309
after 4days accurarcy is 0.4088397790055249
after 5days accurarcy is 0.4088397790055249
after 6days accurarcy is 0.4419889502762431
after 7days accurarcy is 0.44751381215469616


In [289]:
df_final2

cluster_no
Datetime             
2021-06-27    Neutral
2021-06-28    Neutral
2021-06-29    Neutral
2021-06-30      Greed
2021-07-01      Greed
...               ...
2021-12-22      Greed
2021-12-23      Greed
2021-12-24      Greed
2021-12-25      Greed
2021-12-26      Greed

[181 rows x 1 columns]

In [286]:
for i in range(len(df_final2)):
  if df_final2.iloc[i,0] == 'Fear':
    df_final2.iloc[i,0] = 'Greed'
  elif df_final2.iloc[i,0] == 'Greed':
    df_final2.iloc[i,0] = 'Fear'

In [288]:
for k in range(8):
  scores = 0  
  for i in range(180):
    if df_final2.iloc[i,0] == label.iloc[i+k,1]:
      scores += 1
  print(f'after {k}days accurarcy is {scores/181}')

after 0days accurarcy is 0.35911602209944754
after 1days accurarcy is 0.35359116022099446
after 2days accurarcy is 0.34806629834254144
after 3days accurarcy is 0.36464088397790057
after 4days accurarcy is 0.3425414364640884
after 5days accurarcy is 0.3425414364640884
after 6days accurarcy is 0.35911602209944754
after 7days accurarcy is 0.35359116022099446


In [283]:
df_final2.iloc[1,0]

'Neutral'

In [290]:
label.describe()

Datetime Class
count          188   188
unique         188     3
top     2021-10-11  Fear
freq             1    89

In [293]:
df_final.describe()

cluster_no
count         181
unique          3
top         Greed
freq          142